#export_generator.py
import json
import yaml
from typing import Dict, List, Any, Optional, Set, Tuple, Callable
from datetime import datetime
from pathlib import Path
from abc import ABC, abstractmethod
from enum import Enum
from dataclasses import dataclass
import toml
import logging
from ..core.utils import compare_versions

logger = logging.getLogger(__name__)


class PackageEcosystem(Enum):
    """Supported package ecosystems"""
    PYPI = "pypi"
    NPM = "npm"
    CONDA = "conda"
    MAVEN = "maven"
    CARGO = "crates"
    GOMODULES = "gomodules" 
    APT = "apt"
    APK = "apk"  
    COCOAPODS = "cocoapods"  
    RUBYGEMS = "rubygems" 
    PACKAGIST = "packagist"  
    NUGET = "nuget" 
    HOMEBREW = "homebrew"  
    CONAN = "conan"
    VCPKG = "vcpkg"
    SYSTEM = "system"
    UNKNOWN = "unknown"


@dataclass
class PackageInfo:
    """Structured package information"""
    name: str
    version: str
    ecosystem: PackageEcosystem
    extras: Optional[Dict[str, Any]] = None
    
    @classmethod
    def from_dict(cls, name: str, info: Dict[str, Any]) -> 'PackageInfo':
        """Create PackageInfo from dictionary"""
        ecosystem_str = info.get('ecosystem', 'unknown')
        try:
            ecosystem = PackageEcosystem(ecosystem_str)
        except ValueError:
            ecosystem = PackageEcosystem.UNKNOWN
            
        return cls(
            name=name,
            version=info.get('version', ''),
            ecosystem=ecosystem,
            extras=info.get('extras', {})
        )


class ExportFormat(ABC):
    """Abstract base class for export formats"""
    
    @abstractmethod
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        """Generate output in specific format"""
        pass
    
    def _generate_header(self, comment_prefix: str = "#") -> List[str]:
        """Generate common header for files"""
        return [
            f"{comment_prefix} Generated by Universal Dependency Resolver",
            f"{comment_prefix} Date: {datetime.now().isoformat()}",
            f"{comment_prefix} Do not edit manually - this file is auto-generated",
            ""
        ]
    
    def _filter_packages(self, packages: List[PackageInfo], 
                        ecosystems: Set[PackageEcosystem]) -> List[PackageInfo]:
        """Filter packages by ecosystem"""
        return [pkg for pkg in packages if pkg.ecosystem in ecosystems]


class RequirementsTxtFormat(ExportFormat):
    """Generate Python requirements.txt"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        lines = self._generate_header()
        
        # Add system information
        os_info = system_info.get('os', {})
        lines.extend([
            f"# System: {os_info.get('system', 'Unknown')} {os_info.get('release', '')}",
            f"# Architecture: {os_info.get('machine', 'Unknown')}",
        ])
        
        # Add Python version constraint
        runtime_versions = system_info.get('runtime_versions', {})
        python_info = runtime_versions.get('python', {})
        if python_version := python_info.get('version'):
            lines.extend([
                f"# Python: {python_version}",
                ""
            ])
        
        # Filter Python packages
        python_packages = self._filter_packages(packages, {PackageEcosystem.PYPI})
        
        # Group packages by category if specified
        if options.get('group_by_category', False):
            categorized = self._categorize_packages(python_packages)
            for category, pkgs in categorized.items():
                if pkgs:
                    lines.extend([f"# {category}", ""])
                    lines.extend(self._format_packages(pkgs, options))
                    lines.append("")
        else:
            lines.extend(self._format_packages(python_packages, options))
        
        # Add index URLs
        if options.get('include_index_url', True):
            lines.extend(self._generate_index_urls(system_info))
        
        # Add hash verification if requested
        if options.get('include_hashes', False):
            lines.extend(self._generate_hash_requirements(python_packages))
        
        return '\n'.join(lines).strip()
    
    def _format_packages(self, packages: List[PackageInfo], 
                        options: Dict[str, Any]) -> List[str]:
        """Format package specifications"""
        lines = []
        pin_versions = options.get('pin_versions', True)
        
        # Sort packages by name, then by version (newest first) - ENHANCED SORTING
        sorted_packages = sorted(
            packages, 
            key=lambda p: (p.name.lower(), p.version),
            # Use compare_versions for proper version sorting
            reverse=False
        )
        
        # If we have duplicate packages with different versions, keep only the latest
        if options.get('deduplicate', True):
            seen_packages = {}
            for pkg in sorted_packages:
                if pkg.name not in seen_packages:
                    seen_packages[pkg.name] = pkg
                else:
                    # Compare versions and keep the newer one
                    if compare_versions(pkg.version, seen_packages[pkg.name].version) > 0:  # ADD THIS
                        seen_packages[pkg.name] = pkg
            sorted_packages = list(seen_packages.values())
        
        # Sort again by name only for final output
        sorted_packages.sort(key=lambda p: p.name.lower())
        
        for pkg in sorted_packages:
            if pin_versions:
                spec = f"{pkg.name}=={pkg.version}"
            else:
                spec = f"{pkg.name}>={pkg.version}"
            
            # Add extras if present
            if pkg.extras and pkg.extras.get('extras'):
                extras_list = pkg.extras['extras']
                spec = f"{pkg.name}[{','.join(extras_list)}]=={pkg.version}"
            
            # Add environment markers
            if pkg.extras and pkg.extras.get('markers'):
                spec += f" ; {pkg.extras['markers']}"
            
            lines.append(spec)
            
        return lines
    
    def _categorize_packages(self, packages: List[PackageInfo]) -> Dict[str, List[PackageInfo]]:
        """Categorize packages by type"""
        categories = {
            'Core Dependencies': [],
            'Development Tools': [],
            'Testing': [],
            'Documentation': [],
            'Other': []
        }
        
        dev_patterns = ['dev', 'debug', 'lint', 'format', 'black', 'flake8', 'mypy']
        test_patterns = ['test', 'pytest', 'unittest', 'mock', 'coverage']
        doc_patterns = ['sphinx', 'doc', 'mkdocs']
        
        for pkg in packages:
            name_lower = pkg.name.lower()
            
            if any(pattern in name_lower for pattern in dev_patterns):
                categories['Development Tools'].append(pkg)
            elif any(pattern in name_lower for pattern in test_patterns):
                categories['Testing'].append(pkg)
            elif any(pattern in name_lower for pattern in doc_patterns):
                categories['Documentation'].append(pkg)
            else:
                categories['Core Dependencies'].append(pkg)
        
        # Remove empty categories
        return {k: v for k, v in categories.items() if v}
    
    def _generate_index_urls(self, system_info: Dict[str, Any]) -> List[str]:
        """Generate index URL configuration"""
        lines = ["", "# Package indexes"]
        lines.append("--index-url https://pypi.org/simple")
        
        # Add PyTorch index for CUDA
        gpu_info = system_info.get('gpu', {})
        if gpu_info.get('available') and gpu_info.get('cuda'):
            cuda_version = gpu_info['cuda'].replace('.', '')
            lines.append(f"--extra-index-url https://download.pytorch.org/whl/cu{cuda_version}")
        
        return lines
    
    def _generate_hash_requirements(self, packages: List[PackageInfo]) -> List[str]:
        """Generate requirements with hash verification"""
        lines = ["", "# Hash verification", "# Run: pip install --require-hashes -r requirements.txt"]
        # In a real implementation, we would fetch actual hashes
        for pkg in packages:
            lines.append(f"# {pkg.name}=={pkg.version} --hash=sha256:...")
        return lines


class PackageJsonFormat(ExportFormat):
    """Generate package.json for Node.js"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        npm_packages = self._filter_packages(packages, {PackageEcosystem.NPM})
        
        package_json = {
            "name": options.get('project_name', 'my-project'),
            "version": options.get('project_version', '1.0.0'),
            "description": options.get('description', 'Generated by Universal Dependency Resolver'),
            "main": options.get('main', 'index.js'),
            "scripts": self._generate_scripts(options),
            "keywords": options.get('keywords', []),
            "author": options.get('author', ''),
            "license": options.get('license', 'MIT'),
            "dependencies": {},
            "devDependencies": {},
            "peerDependencies": {},
            "engines": self._generate_engines(system_info),
            "repository": options.get('repository', {}),
            "bugs": options.get('bugs', {}),
            "homepage": options.get('homepage', '')
        }
        
        # Categorize packages
        for pkg in npm_packages:
            version = self._format_npm_version(pkg.version, options)
            
            if pkg.extras and pkg.extras.get('dev', False):
                package_json['devDependencies'][pkg.name] = version
            elif pkg.extras and pkg.extras.get('peer', False):
                package_json['peerDependencies'][pkg.name] = version
            else:
                package_json['dependencies'][pkg.name] = version
        
        # Add npm configuration
        if options.get('include_npm_config', False):
            package_json['publishConfig'] = {
                'registry': 'https://registry.npmjs.org/'
            }
        
        # Remove empty fields
        package_json = {k: v for k, v in package_json.items() 
                       if v or k in ['dependencies', 'devDependencies']}
        
        return json.dumps(package_json, indent=2)
    
    def _format_npm_version(self, version: str, options: Dict[str, Any]) -> str:
        """Format version string for npm"""
        if options.get('pin_versions', True):
            return version
        elif options.get('use_caret', True):
            return f"^{version}"
        else:
            return f"~{version}"
    
    def _generate_scripts(self, options: Dict[str, Any]) -> Dict[str, str]:
        """Generate npm scripts"""
        scripts = {
            "test": options.get('test_command', 'echo "Error: no test specified" && exit 1'),
        }
        
        if options.get('include_standard_scripts', True):
            scripts.update({
                "start": "node index.js",
                "build": "echo 'No build step'",
                "lint": "eslint .",
                "format": "prettier --write ."
            })
        
        return scripts
    
    def _generate_engines(self, system_info: Dict[str, Any]) -> Dict[str, str]:
        """Generate engine requirements"""
        engines = {}
        runtime_versions = system_info.get('runtime_versions', {})
        
        if node_info := runtime_versions.get('node'):
            engines['node'] = f">={node_info.get('version', '14.0.0')}"
        
        if npm_info := runtime_versions.get('npm'):
            engines['npm'] = f">={npm_info.get('version', '6.0.0')}"
        
        return engines


class DockerfileFormat(ExportFormat):
    """Generate optimized Dockerfile"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        lines = []
        
        # Determine base image
        base_image = self._determine_base_image(packages, system_info, options)
        
        # Multi-stage build if requested
        if options.get('multi_stage', True):
            lines.extend(self._generate_multi_stage(base_image, packages, system_info, options))
        else:
            lines.extend(self._generate_single_stage(base_image, packages, system_info, options))
        
        return '\n'.join(lines)
    
    def _determine_base_image(self, packages: List[PackageInfo], 
                             system_info: Dict[str, Any], 
                             options: Dict[str, Any]) -> str:
        """Determine optimal base image"""
        if custom_base := options.get('base_image'):
            return custom_base
        
        # Check for GPU requirements
        gpu_info = system_info.get('gpu', {})
        if gpu_info.get('available') and gpu_info.get('cuda'):
            cuda_version = gpu_info['cuda']
            return f"nvidia/cuda:{cuda_version}-cudnn8-runtime-ubuntu22.04"
        
        # Check for language-specific requirements
        has_python = any(pkg.ecosystem == PackageEcosystem.PYPI for pkg in packages)
        has_node = any(pkg.ecosystem == PackageEcosystem.NPM for pkg in packages)
        has_ruby = any(pkg.ecosystem == PackageEcosystem.RUBYGEMS for pkg in packages)  
        has_php = any(pkg.ecosystem == PackageEcosystem.PACKAGIST for pkg in packages) 
        has_dotnet = any(pkg.ecosystem == PackageEcosystem.NUGET for pkg in packages) 
        has_go = any(pkg.ecosystem == PackageEcosystem.GOMODULES for pkg in packages)
        
        # Multi-language images
        if has_python and has_node:
           return "python:3.11-slim"
        elif has_python:
           return "python:3.11-slim"
        elif has_node:
           return "node:18-alpine"
        elif has_ruby:  # ADD
           return "ruby:3.2-slim"
        elif has_php:  # ADD
           return "php:8.2-cli"
        elif has_dotnet:  # ADD
           return "mcr.microsoft.com/dotnet/sdk:7.0"
        elif has_go:  # ADD
           return "golang:1.21-alpine"
        else:
           return "ubuntu:22.04"
    
    def _generate_multi_stage(self, base_image: str, packages: List[PackageInfo],
                             system_info: Dict[str, Any], options: Dict[str, Any]) -> List[str]:
        """Generate multi-stage Dockerfile"""
        lines = self._generate_header()
        
        # Builder stage
        lines.extend([
            "# Builder stage",
            f"FROM {base_image} AS builder",
            "",
            "WORKDIR /build",
            ""
        ])
        
        # Install build dependencies
        lines.extend(self._install_build_dependencies(packages))
        
        # Copy dependency files
        lines.extend(self._copy_dependency_files(packages))
        
        # Install dependencies
        lines.extend(self._install_dependencies(packages, build_stage=True))
        
        # Runtime stage
        lines.extend([
            "",
            "# Runtime stage",
            f"FROM {base_image}",
            "",
            "WORKDIR /app",
            ""
        ])
        
        # Install runtime dependencies only
        lines.extend(self._install_runtime_dependencies(packages))
        
        # Copy from builder
        lines.extend([
            "",
            "# Copy installed packages from builder",
            "COPY --from=builder /usr/local /usr/local",
            ""
        ])
        
        # Add health check
        if options.get('health_check', True):
            lines.extend(self._generate_health_check(options))
        
        # Set up non-root user
        if options.get('non_root_user', True):
            lines.extend(self._create_non_root_user())
        
        # Add labels
        lines.extend(self._generate_labels(options))
        
        # Set entrypoint
        lines.extend(self._generate_entrypoint(options))
        
        return lines
    
    def _generate_single_stage(self, base_image: str, packages: List[PackageInfo],
                              system_info: Dict[str, Any], options: Dict[str, Any]) -> List[str]:
        """Generate single-stage Dockerfile"""
        lines = self._generate_header()
        
        lines.extend([
            f"FROM {base_image}",
            "",
            "WORKDIR /app",
            ""
        ])
        
        # Install system dependencies
        lines.extend(self._install_system_dependencies(packages))
        
        # Install language-specific packages
        lines.extend(self._install_dependencies(packages, build_stage=False))
        
        # Add health check
        if options.get('health_check', True):
            lines.extend(self._generate_health_check(options))
        
        # Set entrypoint
        lines.extend(self._generate_entrypoint(options))
        
        return lines
    
    def _install_build_dependencies(self, packages: List[PackageInfo]) -> List[str]:
        """Install build-time dependencies"""
        lines = ["# Install build dependencies"]
        
        has_python = any(pkg.ecosystem == PackageEcosystem.PYPI for pkg in packages)
        has_node = any(pkg.ecosystem == PackageEcosystem.NPM for pkg in packages)
        has_cpp = any(pkg.ecosystem in [PackageEcosystem.CONAN, PackageEcosystem.VCPKG] for pkg in packages)
        
        deps = ["apt-get update"]
        
        if has_python:
            deps.append("apt-get install -y python3-dev python3-pip build-essential")
        if has_node:
            deps.append("apt-get install -y nodejs npm")
        if has_cpp:
            deps.append("apt-get install -y cmake g++ git")
        
        deps.append("rm -rf /var/lib/apt/lists/*")
        
        lines.append("RUN " + " && \\\n    ".join(deps))
        lines.append("")
        
        return lines
    
    def _install_system_dependencies(self, packages: List[PackageInfo]) -> List[str]:
        """Install system-level dependencies"""
        apt_packages = self._filter_packages(packages, {PackageEcosystem.APT})
        
        if not apt_packages:
            return []
        
        lines = ["# Install system packages"]
        cmd_parts = ["apt-get update"]
        
        for pkg in apt_packages:
            cmd_parts.append(f"apt-get install -y {pkg.name}")
        
        cmd_parts.append("rm -rf /var/lib/apt/lists/*")
        
        lines.append("RUN " + " && \\\n    ".join(cmd_parts))
        lines.append("")
        
        return lines
    
    def _install_dependencies(self, packages: List[PackageInfo], 
                             build_stage: bool = False) -> List[str]:
        """Install language-specific dependencies"""
        lines = []
        
        # Python packages
        python_packages = self._filter_packages(packages, {PackageEcosystem.PYPI})
        if python_packages:
            lines.extend(self._install_python_packages(python_packages, build_stage))
        
        # Node packages
        npm_packages = self._filter_packages(packages, {PackageEcosystem.NPM})
        if npm_packages:
            lines.extend(self._install_npm_packages(npm_packages, build_stage))
        
        return lines
    
    def _install_python_packages(self, packages: List[PackageInfo], 
                                build_stage: bool) -> List[str]:
        """Install Python packages"""
        lines = ["# Install Python packages"]
        
        if build_stage:
            # Use requirements file for better caching
            requirements = []
            for pkg in packages:
                requirements.append(f"{pkg.name}=={pkg.version}")
            
            lines.extend([
                "COPY requirements.txt .",
                "RUN pip install --no-cache-dir -r requirements.txt",
                ""
            ])
        else:
            # Direct installation
            pkg_list = ' '.join([f"{pkg.name}=={pkg.version}" for pkg in packages])
            lines.extend([
                f"RUN pip install --no-cache-dir {pkg_list}",
                ""
            ])
        
        return lines
    
    def _install_npm_packages(self, packages: List[PackageInfo], 
                             build_stage: bool) -> List[str]:
        """Install Node.js packages"""
        lines = ["# Install Node.js packages"]
        
        if build_stage:
            lines.extend([
                "COPY package*.json .",
                "RUN npm ci --only=production",
                ""
            ])
        else:
            for pkg in packages:
                lines.append(f"RUN npm install -g {pkg.name}@{pkg.version}")
            lines.append("")
        
        return lines
    
    def _copy_dependency_files(self, packages: List[PackageInfo]) -> List[str]:
        """Copy dependency files for caching"""
        lines = ["# Copy dependency files"]
        
        has_python = any(pkg.ecosystem == PackageEcosystem.PYPI for pkg in packages)
        has_node = any(pkg.ecosystem == PackageEcosystem.NPM for pkg in packages)
        
        if has_python:
            lines.append("COPY requirements.txt* pyproject.toml* setup.py* ./")
        if has_node:
            lines.append("COPY package*.json ./")
        
        lines.append("")
        return lines
    
    def _install_runtime_dependencies(self, packages: List[PackageInfo]) -> List[str]:
        """Install only runtime dependencies"""
        lines = ["# Install runtime dependencies"]
        lines.append("RUN apt-get update && apt-get install -y --no-install-recommends \\")
        
        runtime_deps = ["    python3", "    libpython3-stdlib"]
        
        # Add specific runtime libraries
        if any('numpy' in pkg.name for pkg in packages):
            runtime_deps.append("    libopenblas-base")
        if any('pillow' in pkg.name.lower() for pkg in packages):
            runtime_deps.append("    libjpeg62-turbo")
        
        lines.extend(runtime_deps)
        lines.extend([
            "    && rm -rf /var/lib/apt/lists/*",
            ""
        ])
        
        return lines
    
    def _create_non_root_user(self) -> List[str]:
        """Create non-root user for security"""
        return [
            "",
            "# Create non-root user",
            "RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app",
            "USER appuser",
            ""
        ]
    
    def _generate_health_check(self, options: Dict[str, Any]) -> List[str]:
        """Generate Docker health check"""
        health_cmd = options.get('health_check_cmd', 'curl -f http://localhost:8080/health || exit 1')
        
        return [
            "",
            "# Health check",
            f'HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \\',
            f'  CMD {health_cmd}',
            ""
        ]
    
    def _generate_labels(self, options: Dict[str, Any]) -> List[str]:
        """Generate Docker labels"""
        lines = ["", "# Labels"]
        
        labels = {
            'maintainer': options.get('maintainer', ''),
            'version': options.get('version', '1.0.0'),
            'description': options.get('description', 'Generated by Universal Dependency Resolver'),
            'build-date': datetime.now().isoformat()
        }
        
        for key, value in labels.items():
            if value:
                lines.append(f'LABEL {key}="{value}"')
        
        lines.append("")
        return lines
    
    def _generate_entrypoint(self, options: Dict[str, Any]) -> List[str]:
        """Generate container entrypoint"""
        entrypoint = options.get('entrypoint', [])
        cmd = options.get('cmd', [])
        
        lines = ["# Entrypoint"]
        
        if entrypoint:
            lines.append(f"ENTRYPOINT {json.dumps(entrypoint)}")
        
        if cmd:
            lines.append(f"CMD {json.dumps(cmd)}")
        elif not entrypoint:
            lines.append('CMD ["/bin/bash"]')
        
        return lines

class GemfileFormat(ExportFormat):
    """Generate Gemfile for Ruby"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        lines = self._generate_header()
        lines.extend([
            'source "https://rubygems.org"',
            '',
            f'ruby "{options.get("ruby_version", "3.2.0")}"',
            ''
        ])
        
        # Filter Ruby packages
        ruby_packages = self._filter_packages(packages, {PackageEcosystem.RUBYGEMS})
        
        # Group packages
        groups = {
            'default': [],
            'development': [],
            'test': []
        }
        
        for pkg in ruby_packages:
            group = pkg.extras.get('group', 'default') if pkg.extras else 'default'
            if group not in groups:
                groups[group] = []
            groups[group].append(pkg)
        
        # Write default group
        for pkg in sorted(groups['default'], key=lambda p: p.name.lower()):
            if options.get('pin_versions', True):
                lines.append(f'gem "{pkg.name}", "{pkg.version}"')
            else:
                lines.append(f'gem "{pkg.name}", "~> {pkg.version}"')
        
        # Write other groups
        for group_name, pkgs in groups.items():
            if group_name != 'default' and pkgs:
                lines.extend(['', f'group :{group_name} do'])
                for pkg in sorted(pkgs, key=lambda p: p.name.lower()):
                    if options.get('pin_versions', True):
                        lines.append(f'  gem "{pkg.name}", "{pkg.version}"')
                    else:
                        lines.append(f'  gem "{pkg.name}", "~> {pkg.version}"')
                lines.append('end')
        
        return '\n'.join(lines)

class ComposerJsonFormat(ExportFormat):
    """Generate composer.json for PHP"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        php_packages = self._filter_packages(packages, {PackageEcosystem.PACKAGIST})
        
        composer_json = {
            "name": options.get('vendor_name', 'vendor') + '/' + options.get('project_name', 'project'),
            "description": options.get('description', 'Generated by Universal Dependency Resolver'),
            "type": options.get('type', 'library'),
            "license": options.get('license', 'MIT'),
            "authors": [
                {
                    "name": options.get('author_name', 'Your Name'),
                    "email": options.get('author_email', 'you@example.com')
                }
            ],
            "minimum-stability": options.get('minimum_stability', 'stable'),
            "require": {},
            "require-dev": {},
            "autoload": {
                "psr-4": {
                    options.get('namespace', 'App') + "\\": "src/"
                }
            }
        }
        
        # Add PHP version requirement
        if runtime_versions := system_info.get('runtime_versions', {}):
            if php_info := runtime_versions.get('php'):
                composer_json['require']['php'] = f">={php_info.get('version', '8.0')}"
        
        # Add packages
        for pkg in php_packages:
            version = self._format_composer_version(pkg.version, options)
            
            if pkg.extras and pkg.extras.get('dev', False):
                composer_json['require-dev'][pkg.name] = version
            else:
                composer_json['require'][pkg.name] = version
        
        return json.dumps(composer_json, indent=4)
    
    def _format_composer_version(self, version: str, options: Dict[str, Any]) -> str:
        """Format version for Composer"""
        if options.get('pin_versions', True):
            return version
        else:
            return f"^{version}"

class GoModFormat(ExportFormat):
    """Generate go.mod for Go"""
    
    def generate(self, packages: List[PackageInfo], 
                system_info: Dict[str, Any], 
                options: Dict[str, Any]) -> str:
        lines = self._generate_header('//')
        
        go_packages = self._filter_packages(packages, {PackageEcosystem.GOMODULES})
        
        lines.extend([
            f'module {options.get("module_name", "example.com/myproject")}',
            '',
            f'go {options.get("go_version", "1.21")}',
            ''
        ])
        
        if go_packages:
            lines.append('require (')
            for pkg in sorted(go_packages, key=lambda p: p.name.lower()):
                lines.append(f'\t{pkg.name} v{pkg.version}')
            lines.extend([')', ''])
        
        # Add replace directives if specified
        if replacements := options.get('replace'):
            lines.append('replace (')
            for old, new in replacements.items():
                lines.append(f'\t{old} => {new}')
            lines.append(')')
        
        return '\n'.join(lines)                            


class ExportGenerator:
    """Main export generator with plugin architecture"""
    
    def __init__(self):
        self.formats: Dict[str, ExportFormat] = {
            'requirements.txt': RequirementsTxtFormat(),
            'package.json': PackageJsonFormat(),
            'Dockerfile': DockerfileFormat(),
            'Gemfile': GemfileFormat(), 
            'composer.json': ComposerJsonFormat(), 
            'go.mod': GoModFormat(),
            # Add more formats as needed
        }
        
        # Legacy format generators (to be refactored)
        self.legacy_generators = {
            'environment.yml': self._generate_conda_env,
            'pyproject.toml': self._generate_pyproject_toml,
            'docker-compose.yml': self._generate_docker_compose,
            'install.sh': self._generate_install_script,
            'install.bat': self._generate_install_batch,
            'CMakeLists.txt': self._generate_cmake,
            'Cargo.toml': self._generate_cargo_toml,
            'build.gradle': self._generate_gradle,
            'pom.xml': self._generate_maven
        }
    
    def register_format(self, name: str, format_handler: ExportFormat) -> None:
        """Register a new export format"""
        self.formats[name] = format_handler
    
    def generate(self, 
                resolved_packages: Dict[str, Any], 
                format: str, 
                system_info: Optional[Dict[str, Any]] = None,
                options: Optional[Dict[str, Any]] = None) -> str:
        """Generate output in specified format"""
        if not resolved_packages:
            raise ValueError("No packages provided")
        
        # Convert packages to structured format
        packages = self._parse_packages(resolved_packages)
        
        # Use new format handler if available
        if format in self.formats:
            return self.formats[format].generate(
                packages, 
                system_info or {}, 
                options or {}
            )
        
        # Fall back to legacy generators
        if format in self.legacy_generators:
            return self.legacy_generators[format](
                resolved_packages, 
                system_info or {}, 
                options or {}
            )
        
        raise ValueError(f"Unsupported format: {format}")
    
    def generate_multiple(self,
                         resolved_packages: Dict[str, Any],
                         formats: List[str],
                         system_info: Optional[Dict[str, Any]] = None,
                         options: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
        """Generate multiple export formats"""
        results = {}
        
        for format in formats:
            try:
                results[format] = self.generate(
                    resolved_packages,
                    format,
                    system_info,
                    options
                )
            except Exception as e:
                logger.error(f"Failed to generate {format}: {e}")
                results[format] = f"# Error generating {format}: {str(e)}"
        
        return results
    
    def save_to_file(self, 
                    content: str, 
                    filepath: Path, 
                    format: str) -> None:
        """Save generated content to file"""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        # Set appropriate file permissions for scripts
        if format in ['install.sh']:
            filepath.write_text(content)
            filepath.chmod(0o755)
        else:
            filepath.write_text(content)
    
    def _parse_packages(self, resolved_packages: Dict[str, Any]) -> List[PackageInfo]:
        """Parse resolved packages into structured format"""
        packages = []
        
        package_dict = resolved_packages.get('resolved_packages', resolved_packages)
        
        for name, info in package_dict.items():
            if isinstance(info, dict):
                packages.append(PackageInfo.from_dict(name, info))
            else:
                logger.warning(f"Invalid package info for {name}: {info}")
        
        return packages

    def _deduplicate_packages(self, packages: List[PackageInfo]) -> List[PackageInfo]:
        """Remove duplicate packages, keeping the latest version"""
        package_map = {}
        
        for pkg in packages:
            key = (pkg.name, pkg.ecosystem)
            if key not in package_map:
                package_map[key] = pkg
            else:
                # Compare versions and keep the newer one
                existing_pkg = package_map[key]
                if compare_versions(pkg.version, existing_pkg.version) > 0:  # ADD THIS
                    package_map[key] = pkg
                    logger.info(f"Deduplicating {pkg.name}: keeping {pkg.version} over {existing_pkg.version}")
        
        return list(package_map.values())
    
    def _find_conflicting_versions(self, packages: List[PackageInfo]) -> Dict[str, List[PackageInfo]]:
        """Find packages with multiple versions"""
        conflicts = {}
        package_versions = {}
        
        for pkg in packages:
            key = (pkg.name, pkg.ecosystem)
            if key not in package_versions:
                package_versions[key] = []
            package_versions[key].append(pkg)
        
        for key, versions in package_versions.items():
            if len(versions) > 1:
                # Sort by version (newest first)
                sorted_versions = sorted(
                    versions,
                    key=lambda p: p.version,
                    reverse=True,
                    # Use compare_versions for proper sorting
                    cmp=lambda x, y: compare_versions(x.version, y.version)  # Note: In Python 3, use key with functools.cmp_to_key
                )
                conflicts[f"{key[0]} ({key[1].value})"] = sorted_versions
        
        return conflicts
    
    def generate(self, 
                resolved_packages: Dict[str, Any], 
                format: str, 
                system_info: Optional[Dict[str, Any]] = None,
                options: Optional[Dict[str, Any]] = None) -> str:
        """Generate output in specified format"""
        if not resolved_packages:
            raise ValueError("No packages provided")
        
        # Convert packages to structured format
        packages = self._parse_packages(resolved_packages)
        
        # Deduplicate packages if requested
        if options and options.get('deduplicate', False):
            packages = self._deduplicate_packages(packages)  # ADD THIS
        
        # Check for version conflicts
        if options and options.get('check_conflicts', False):
            conflicts = self._find_conflicting_versions(packages)  # ADD THIS
            if conflicts:
                logger.warning(f"Found version conflicts: {conflicts}")
        
        # Use new format handler if available
        if format in self.formats:
            return self.formats[format].generate(
                packages, 
                system_info or {}, 
                options or {}
            )
        
        # Fall back to legacy generators
        if format in self.legacy_generators:
            return self.legacy_generators[format](
                resolved_packages, 
                system_info or {}, 
                options or {}
            )
        
        raise ValueError(f"Unsupported format: {format}")   
    
    # Legacy format generators (keeping for backward compatibility)
    # In the legacy generator methods, add version comparison where useful:
    def _generate_conda_env(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate Conda environment.yml"""
        env_dict = {
            'name': options.get('env_name', 'myenv'),
            'channels': ['defaults', 'conda-forge'],
            'dependencies': []
        }
        
        # Add channels based on packages
        package_names = str(packages.get('resolved_packages', {}))
        if 'cuda' in package_names or 'torch' in package_names:
            env_dict['channels'].extend(['pytorch', 'nvidia'])
        
        # Group packages by ecosystem
        conda_packages = []
        pip_packages = []
        
        for name, info in packages.get('resolved_packages', {}).items():
            version = info.get('version', '')
            ecosystem = info.get('ecosystem', '')
            
            if ecosystem == 'conda':
                conda_packages.append((name, version))
            elif ecosystem == 'pypi':
                pip_packages.append((name, version))

        # Sort packages by name and version - ENHANCED
        conda_packages.sort(key=lambda x: x[0].lower())
        pip_packages.sort(key=lambda x: x[0].lower())
        
        # If we have duplicate packages, keep only the latest version
        if options.get('deduplicate', True):
            conda_packages = self._deduplicate_package_list(conda_packages)  
            pip_packages = self._deduplicate_package_list(pip_packages)         
        
        # Add Python version
        if system_info and 'runtime_versions' in system_info:
            python_version = system_info['runtime_versions'].get('python', {}).get('version', '')
            if python_version:
                # Convert to conda format (e.g., 3.9.0 -> 3.9)
                conda_python_version = '.'.join(python_version.split('.')[:2])
                env_dict['dependencies'].append(f"python={conda_python_version}")
        
        # Add conda packages
        for name, version in conda_packages:
            if options.get('pin_versions', True):
                env_dict['dependencies'].append(f"{name}={version}")
            else:
                env_dict['dependencies'].append(f"{name}>={version}")
        
        # Add pip packages
        if pip_packages:
            pip_deps = []
            for name, version in pip_packages:
                if options.get('pin_versions', True):
                    pip_deps.append(f"{name}=={version}")
                else:
                    pip_deps.append(f"{name}>={version}")
            env_dict['dependencies'].append({'pip': pip_deps})
        
        # Add optional sections
        if options.get('include_platforms'):
            env_dict['platforms'] = ['linux-64', 'osx-64', 'win-64']
        
        return yaml.dump(env_dict, default_flow_style=False, sort_keys=False)

    def _deduplicate_package_list(self, package_list: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
        """Deduplicate a list of (name, version) tuples, keeping the latest version"""
        package_map = {}
        
        for name, version in package_list:
            if name not in package_map:
                package_map[name] = version
            else:
                # Compare versions and keep the newer one
                if compare_versions(version, package_map[name]) > 0:  # ADD THIS
                    package_map[name] = version
                    logger.info(f"Deduplicating {name}: keeping {version} over {package_map[name]}")
        
        return [(name, version) for name, version in package_map.items()] 

    def _sort_packages_by_version(self, packages: List[Dict[str, Any]], reverse: bool = True) -> List[Dict[str, Any]]:
        """Sort packages by version using compare_versions"""
        # Convert compare_versions to a key function
        from functools import cmp_to_key
        
        def version_comparator(pkg1, pkg2):
            v1 = pkg1.get('version', '0.0.0')
            v2 = pkg2.get('version', '0.0.0')
            return compare_versions(v1, v2)
        
        return sorted(packages, key=cmp_to_key(version_comparator), reverse=reverse)  # ADD THIS
    
    def _get_latest_version(self, versions: List[str]) -> Optional[str]:
        """Get the latest version from a list of version strings"""
        if not versions:
            return None
        
        latest = versions[0]
        for v in versions[1:]:
            if compare_versions(v, latest) > 0:  # ADD THIS
                latest = v
        
        return latest
    
    def _filter_version_range(self, versions: List[str], min_version: Optional[str] = None, 
                            max_version: Optional[str] = None) -> List[str]:
        """Filter versions within a specific range"""
        filtered = []
        
        for v in versions:
            include = True
            
            if min_version and compare_versions(v, min_version) < 0:  # ADD THIS
                include = False
            
            if max_version and compare_versions(v, max_version) > 0:  # ADD THIS
                include = False
            
            if include:
                filtered.append(v)
        
        return filtered       
    
    def _generate_pyproject_toml(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate Poetry pyproject.toml"""
        pyproject = {
            'tool': {
                'poetry': {
                    'name': options.get('project_name', 'my-project'),
                    'version': options.get('project_version', '0.1.0'),
                    'description': options.get('description', 'Generated by Universal Dependency Resolver'),
                    'authors': [options.get('author', 'Your Name <you@example.com>')],
                    'readme': options.get('readme', 'README.md'),
                    'license': options.get('license', 'MIT'),
                    'homepage': options.get('homepage', ''),
                    'repository': options.get('repository', ''),
                    'keywords': options.get('keywords', []),
                    'classifiers': options.get('classifiers', []),
                    'dependencies': {},
                    'group': {
                        'dev': {
                            'dependencies': {}
                        }
                    }
                }
            }
        }
        
        # Add build system
        pyproject['build-system'] = {
            'requires': ['poetry-core'],
            'build-backend': 'poetry.core.masonry.api'
        }
        
        # Add Python version
        if system_info and 'runtime_versions' in system_info:
            python_version = system_info['runtime_versions'].get('python', {}).get('version', '')
            if python_version:
                major, minor = python_version.split('.')[:2]
                pyproject['tool']['poetry']['dependencies']['python'] = f"^{major}.{minor}"
        
        # Add packages
        python_packages = {
            name: info for name, info in packages.get('resolved_packages', {}).items() 
            if info.get('ecosystem') == 'pypi'
        }
        
        for name, info in python_packages.items():
            version = info['version']
            is_dev = info.get('extras', {}).get('dev', False)
            
            version_spec = f"^{version}" if not options.get('pin_versions', True) else version
            
            if is_dev:
                pyproject['tool']['poetry']['group']['dev']['dependencies'][name] = version_spec
            else:
                pyproject['tool']['poetry']['dependencies'][name] = version_spec
        
        # Add scripts if specified
        if scripts := options.get('scripts'):
            pyproject['tool']['poetry']['scripts'] = scripts
        
        return toml.dumps(pyproject)
    
    def _generate_docker_compose(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate docker-compose.yml"""
        compose = {
            'version': '3.8',
            'services': {}
        }
        
        # Main application service
        app_service = {
            'build': {
                'context': '.',
                'dockerfile': 'Dockerfile'
            },
            'volumes': ['.:/app'],
            'environment': options.get('environment', []),
            'ports': options.get('ports', []),
            'networks': ['app-network']
        }
        
        # Add GPU support if needed
        if system_info and system_info.get('gpu', {}).get('available'):
            app_service['deploy'] = {
                'resources': {
                    'reservations': {
                        'devices': [{
                            'driver': 'nvidia',
                            'count': 'all',
                            'capabilities': ['gpu']
                        }]
                    }
                }
            }
        
        # Add restart policy
        app_service['restart'] = options.get('restart_policy', 'unless-stopped')
        
        # Add health check
        if health_check := options.get('health_check'):
            app_service['healthcheck'] = health_check
        
        compose['services']['app'] = app_service
        
        # Add additional services
        if options.get('include_redis'):
            compose['services']['redis'] = {
                'image': 'redis:alpine',
                'networks': ['app-network'],
                'volumes': ['redis-data:/data']
            }
        
        if options.get('include_postgres'):
            compose['services']['postgres'] = {
                'image': 'postgres:15-alpine',
                'environment': {
                    'POSTGRES_DB': options.get('db_name', 'app'),
                    'POSTGRES_USER': options.get('db_user', 'postgres'),
                    'POSTGRES_PASSWORD': options.get('db_password', 'postgres')
                },
                'volumes': ['postgres-data:/var/lib/postgresql/data'],
                'networks': ['app-network']
            }
        
        # Add networks
        compose['networks'] = {
            'app-network': {
                'driver': 'bridge'
            }
        }
        
        # Add volumes
        volumes = {}
        if options.get('include_redis'):
            volumes['redis-data'] = {}
        if options.get('include_postgres'):
            volumes['postgres-data'] = {}
        
        if volumes:
            compose['volumes'] = volumes
        
        return yaml.dump(compose, default_flow_style=False, sort_keys=False)
    
    def _generate_install_script(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate shell installation script"""
        lines = [
            "#!/usr/bin/env bash",
            "# Generated by Universal Dependency Resolver",
            f"# Date: {datetime.now().isoformat()}",
            "",
            "set -euo pipefail",  # Strict error handling
            "",
            "# Color output",
            'RED="\\033[0;31m"',
            'GREEN="\\033[0;32m"',
            'YELLOW="\\033[0;33m"',
            'NC="\\033[0m"',
            "",
            "# Logging functions",
            'log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }',
            'log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }',
            'log_error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }',
            "",
            'log_info "Starting dependency installation..."',
            ""
        ]
        
        # Add OS detection
        lines.extend([
            "# Detect OS",
            'if [[ "$OSTYPE" == "linux-gnu"* ]]; then',
            '    OS="linux"',
            'elif [[ "$OSTYPE" == "darwin"* ]]; then',
            '    OS="macos"',
            'else',
            '    log_error "Unsupported OS: $OSTYPE"',
            'fi',
            ""
        ])
        
        # Check for required tools
        lines.extend([
            "# Check required tools",
            'check_command() {',
            '    if ! command -v "$1" &> /dev/null; then',
            '        log_error "$1 is required but not installed"',
            '    fi',
            '}',
            ""
        ])
        
        # Group packages by ecosystem
        ecosystems = {}
        for name, info in packages.get('resolved_packages', {}).items():
            ecosystem = info.get('ecosystem', 'unknown')
            if ecosystem not in ecosystems:
                ecosystems[ecosystem] = []
            ecosystems[ecosystem].append((name, info.get('version', '')))
        
        # Install Python packages
        if 'pypi' in ecosystems:
            lines.extend([
                "# Python packages",
                'check_command python3',
                'check_command pip3',
                "",
                'log_info "Installing Python packages..."',
                "",
                "# Upgrade pip",
                "python3 -m pip install --upgrade pip",
                "",
                "# Install packages",
            ])
            
            for name, version in sorted(ecosystems['pypi']):
                lines.append(f'pip3 install "{name}=={version}"')
            
            lines.append("")
        
        # Install Node packages
        if 'npm' in ecosystems:
            lines.extend([
                "# Node.js packages",
                'check_command node',
                'check_command npm',
                "",
                'log_info "Installing Node.js packages..."',
                ""
            ])
            
            for name, version in sorted(ecosystems['npm']):
                lines.append(f'npm install -g "{name}@{version}"')
            
            lines.append("")
 
        # Install Ruby gems
        if 'rubygems' in ecosystems:
           lines.extend([
              "# Ruby gems",
              'check_command ruby',
              'check_command gem',
              "",
              'log_info "Installing Ruby gems..."',
              ""
            ])
    
            for name, version in sorted(ecosystems['rubygems']):
                lines.append(f'gem install "{name}" -v "{version}"')
    
            lines.append("")  

        # Install Go modules
        if 'gomodules' in ecosystems:
            lines.extend([
                "# Go modules",
                'check_command go',
                "",
                'log_info "Installing Go modules..."',
                ""
            ])
    
            for name, version in sorted(ecosystems['gomodules']):
                lines.append(f'go install "{name}@{version}"')
    
            lines.append("")

        # Install PHP packages
        if 'packagist' in ecosystems:
            lines.extend([
                 "# PHP packages",
                 'check_command php',
                 'check_command composer',
                 "",
                 'log_info "Installing PHP packages..."',
                 ""
            ])
    
            for name, version in sorted(ecosystems['packagist']):
                lines.append(f'composer global require "{name}:{version}"')
    
            lines.append("")

        # Install .NET packages
        if 'nuget' in ecosystems:
            lines.extend([
                 "# .NET packages",
                 'check_command dotnet',
                 "",
                 'log_info "Installing .NET packages..."',
                 ""
            ])
    
        for name, version in sorted(ecosystems['nuget']):
            lines.append(f'dotnet tool install --global "{name}" --version "{version}"')
    
        lines.append("")

        # Install Homebrew packages (macOS)
        if 'homebrew' in ecosystems:
            lines.extend([
                 "# Homebrew packages (macOS only)",
                 'if [[ "$OS" == "macos" ]]; then',
                 '    check_command brew',
                 '    log_info "Installing Homebrew packages..."',
            ])
    
            for name, version in sorted(ecosystems['homebrew']):
                if version:
                   lines.append(f'    brew install "{name}@{version}"')
                else:
                    lines.append(f'    brew install "{name}"')
    
             lines.extend(['fi', ''])

        # Install Alpine packages (if in Alpine container)
        if 'apk' in ecosystems:
            lines.extend([
               "# Alpine packages",
               'if command -v apk &> /dev/null; then',
               '    log_info "Installing Alpine packages..."',
               '    apk update',
            ])
    
            for name, version in sorted(ecosystems['apk']):
                if version:
                   lines.append(f'    apk add "{name}={version}"')
                else:
                    lines.append(f'    apk add "{name}"')
    
            lines.extend(['fi', ''])     
        
        # Install system packages
        if 'apt' in ecosystems:
            lines.extend([
                "# System packages (Linux only)",
                'if [[ "$OS" == "linux" ]]; then',
                '    log_info "Installing system packages..."',
                '    if [[ $EUID -ne 0 ]]; then',
                '        SUDO="sudo"',
                '    else',
                '        SUDO=""',
                '    fi',
                '    $SUDO apt-get update',
            ])
            
            for name, _ in ecosystems['apt']:
                lines.append(f'    $SUDO apt-get install -y {name}')
            
            lines.extend(['fi', ''])
        
        # Add verification
        if options.get('verify_installation', True):
            lines.extend([
                "# Verify installation",
                'log_info "Verifying installation..."',
                ""
            ])
            
            if 'pypi' in ecosystems:
                lines.append('python3 -c "import pkg_resources; print(\\"Python packages verified\\")"')
            
            lines.append("")
        
        lines.extend([
            'log_info "Installation completed successfully!"',
            "",
            "# Display summary",
            'echo ""',
            'echo "Installed packages:"',
            f'echo "  Python: {len(ecosystems.get("pypi", []))} packages"',
            f'echo "  Node.js: {len(ecosystems.get("npm", []))} packages"',
            f'echo "  Ruby: {len(ecosystems.get("rubygems", []))} packages"',  # ADD
            f'echo "  Go: {len(ecosystems.get("gomodules", []))} packages"',  
            f'echo "  PHP: {len(ecosystems.get("packagist", []))} packages"',  
            f'echo "  .NET: {len(ecosystems.get("nuget", []))} packages"',  
            f'echo "  System (APT): {len(ecosystems.get("apt", []))} packages"',
            f'echo "  System (APK): {len(ecosystems.get("apk", []))} packages"',  
            f'echo "  macOS: {len(ecosystems.get("homebrew", []))} packages"'  
        ])
        
        return '\n'.join(lines)
    
    def _generate_install_batch(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate Windows batch installation script"""
        lines = [
            "@echo off",
            "REM Generated by Universal Dependency Resolver",
            f"REM Date: {datetime.now().isoformat()}",
            "",
            "setlocal enabledelayedexpansion",
            "",
            "echo ================================",
            "echo Dependency Installation Script",
            "echo ================================",
            "echo.",
            ""
        ]
        
        # Check for admin rights
        if options.get('require_admin', False):
            lines.extend([
                "REM Check for admin rights",
                "net session >nul 2>&1",
                "if %errorLevel% neq 0 (",
                "    echo This script requires administrator privileges.",
                "    echo Please run as administrator.",
                "    pause",
                "    exit /b 1",
                ")",
                ""
            ])
        
        # Group packages by ecosystem
        ecosystems = {}
        for name, info in packages.get('resolved_packages', {}).items():
            ecosystem = info.get('ecosystem', 'unknown')
            if ecosystem not in ecosystems:
                ecosystems[ecosystem] = []
            ecosystems[ecosystem].append((name, info.get('version', '')))
        
        # Install Python packages
        if 'pypi' in ecosystems:
            lines.extend([
                "REM Python packages",
                "echo Checking Python installation...",
                "where python >nul 2>&1",
                "if %errorLevel% neq 0 (",
                "    echo Python is not installed or not in PATH",
                "    echo Please install Python from https://python.org",
                "    pause",
                "    exit /b 1",
                ")",
                "",
                "echo Installing Python packages...",
                "python -m pip install --upgrade pip",
                ""
            ])
            
            for name, version in sorted(ecosystems['pypi']):
                lines.append(f'python -m pip install "{name}=={version}"')
                lines.append(f'if %errorLevel% neq 0 ( echo Failed to install {name} && exit /b 1 )')
            
            lines.append("")
        
        # Install Node packages
        if 'npm' in ecosystems:
            lines.extend([
                "REM Node.js packages",
                "echo Checking Node.js installation...",
                "where npm >nul 2>&1",
                "if %errorLevel% neq 0 (",
                "    echo npm is not installed or not in PATH",
                "    echo Please install Node.js from https://nodejs.org",
                "    pause",
                "    exit /b 1",
                ")",
                "",
                "echo Installing Node.js packages...",
                ""
            ])
            
            for name, version in sorted(ecosystems['npm']):
                lines.append(f'npm install -g "{name}@{version}"')
                lines.append(f'if %errorLevel% neq 0 ( echo Failed to install {name} && exit /b 1 )')
            
            lines.append("")
        
        # Install Chocolatey packages if specified
        if options.get('use_chocolatey') and 'chocolatey' in ecosystems:
            lines.extend([
                "REM Chocolatey packages",
                "echo Checking Chocolatey installation...",
                "where choco >nul 2>&1",
                "if %errorLevel% neq 0 (",
                "    echo Installing Chocolatey...",
                "    @\"%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command \"[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))\"",
                ")",
                "",
                "echo Installing Chocolatey packages...",
                ""
            ])
            
            for name, version in ecosystems['chocolatey']:
                if version:
                    lines.append(f'choco install {name} --version {version} -y')
                else:
                    lines.append(f'choco install {name} -y')
            
            lines.append("")
        
        lines.extend([
            "echo.",
            "echo ================================",
            "echo Installation completed!",
            "echo ================================",
            "",
            "REM Display summary",
            "echo.",
            "echo Installed packages:",
            f"echo   Python: {len(ecosystems.get('pypi', []))} packages",
            f"echo   Node.js: {len(ecosystems.get('npm', []))} packages",
            "",
            "pause"
        ])
        
        return '\r\n'.join(lines)
    
    def _generate_cmake(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate CMakeLists.txt"""
        lines = [
            "# Generated by Universal Dependency Resolver",
            f"# Date: {datetime.now().isoformat()}",
            "",
            f"cmake_minimum_required(VERSION {options.get('cmake_version', '3.16')})",
            f"project({options.get('project_name', 'MyProject')} VERSION {options.get('project_version', '1.0.0')})",
            "",
            "# C++ Standard",
            f"set(CMAKE_CXX_STANDARD {options.get('cpp_standard', '17')})",
            "set(CMAKE_CXX_STANDARD_REQUIRED ON)",
            "set(CMAKE_CXX_EXTENSIONS OFF)",
            "",
            "# Build type",
            'if(NOT CMAKE_BUILD_TYPE)',
            '    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)',
            'endif()',
            ""
        ]
        
        # Add compile options
        lines.extend([
            "# Compile options",
            "if(MSVC)",
            "    add_compile_options(/W4 /WX)",
            "else()",
            "    add_compile_options(-Wall -Wextra -Wpedantic -Werror)",
            "endif()",
            ""
        ])
        
        # Find packages
        cpp_packages = {
            name: info for name, info in packages.get('resolved_packages', {}).items() 
            if info.get('ecosystem') in ['conan', 'vcpkg', 'system']
        }
        
        if cpp_packages:
            lines.append("# Find packages")
            
            for name, info in sorted(cpp_packages.items()):
                version = info.get('version', '')
                components = info.get('extras', {}).get('components', [])
                
                if version:
                    find_cmd = f"find_package({name} {version} REQUIRED"
                else:
                    find_cmd = f"find_package({name} REQUIRED"
                
                if components:
                    find_cmd += f" COMPONENTS {' '.join(components)}"
                
                lines.append(find_cmd + ")")
            
            lines.append("")
        
        # Add CUDA support if needed
        if system_info and system_info.get('gpu', {}).get('cuda'):
            cuda_version = system_info['gpu']['cuda']
            lines.extend([
                "# CUDA support",
                "find_package(CUDA REQUIRED)",
                f"set(CUDA_TOOLKIT_ROOT_DIR /usr/local/cuda-{cuda_version})",
                "set(CMAKE_CUDA_ARCHITECTURES 75 86)",
                "enable_language(CUDA)",
                ""
            ])
        
        # Include directories
        lines.extend([
            "# Include directories",
            "include_directories(",
            "    ${CMAKE_CURRENT_SOURCE_DIR}/include",
            "    ${CMAKE_CURRENT_SOURCE_DIR}/src",
            ")"
        ])
        
        if cpp_packages:
            for name in cpp_packages:
                lines.append(f"    ${{{name.upper()}_INCLUDE_DIRS}}")
        
        lines.extend([")", ""])
        
        # Add source files
        lines.extend([
            "# Source files",
            "file(GLOB_RECURSE SOURCES",
            '    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"',
            '    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc"',
            '    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cxx"',
            ")",
            "",
            "file(GLOB_RECURSE HEADERS",
            '    "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h"',
            '    "${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp"',
            '    "${CMAKE_CURRENT_SOURCE_DIR}/include/*.hxx"',
            ")",
            ""
        ])
        
        # Add executable or library
        project_type = options.get('project_type', 'executable')
        project_name = "${PROJECT_NAME}"
        
        if project_type == 'executable':
            lines.append(f"add_executable({project_name} ${{SOURCES}} ${{HEADERS}})")
        elif project_type == 'static_library':
            lines.append(f"add_library({project_name} STATIC ${{SOURCES}} ${{HEADERS}})")
        elif project_type == 'shared_library':
            lines.append(f"add_library({project_name} SHARED ${{SOURCES}} ${{HEADERS}})")
        
        lines.append("")
        
        # Link libraries
        if cpp_packages:
            lines.append("# Link libraries")
            lines.append(f"target_link_libraries({project_name}")
            lines.append("    PRIVATE")
            
            for name in sorted(cpp_packages):
                lines.append(f"{name}::{name}")
            
            lines.extend([")", ""])
        
        # Installation rules
        if options.get('install_rules', True):
            lines.extend([
                "# Installation",
                f"install(TARGETS {project_name}",
                "    RUNTIME DESTINATION bin",
                "    LIBRARY DESTINATION lib",
                "    ARCHIVE DESTINATION lib",
                ")",
                "",
                "install(DIRECTORY include/",
                "    DESTINATION include",
                "    FILES_MATCHING PATTERN \"*.h\" PATTERN \"*.hpp\"",
                ")"
            ])
        
        # Testing
        if options.get('enable_testing', True):
            lines.extend([
                "",
                "# Testing",
                "enable_testing()",
                "add_subdirectory(tests)"
            ])
        
        return '\n'.join(lines)
    
    def _generate_cargo_toml(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate Cargo.toml for Rust"""
        cargo_toml = toml.loads("""
        [package]
        name = "my-project"
        version = "0.1.0"
        edition = "2021"
        authors = ["Your Name <you@example.com>"]
        description = "Generated by Universal Dependency Resolver"
        license = "MIT"
        repository = ""
        keywords = []
        categories = []
        [dependencies]
        [dev-dependencies]
        [build-dependencies]
        [profile.release]
        lto = true
        codegen-units = 1
        opt-level = 3
        """)
        
        # Update package metadata
        cargo_toml['package']['name'] = options.get('project_name', 'my-project')
        cargo_toml['package']['version'] = options.get('project_version', '0.1.0')
        cargo_toml['package']['authors'] = [options.get('author', 'Your Name <you@example.com>')]
        cargo_toml['package']['description'] = options.get('description', 'Generated by Universal Dependency Resolver')
        
        # Add Rust packages
        rust_packages = {
            name: info for name, info in packages.get('resolved_packages', {}).items() 
            if info.get('ecosystem') == 'crates'
        }
        
        for name, info in rust_packages.items():
            version = info.get('version', '*')
            features = info.get('extras', {}).get('features', [])
            
            if features:
                cargo_toml['dependencies'][name] = {
                    'version': version,
                    'features': features
                }
            else:
                cargo_toml['dependencies'][name] = version
        
        # Add workspace if specified
        if workspace := options.get('workspace'):
            cargo_toml['workspace'] = {'members': workspace}
        
        # Add binary/library targets
        if targets := options.get('targets'):
            cargo_toml['bin'] = targets.get('bin', [])
            cargo_toml['lib'] = targets.get('lib', {})
        
        return toml.dumps(cargo_toml)
    
    def _generate_gradle(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate build.gradle with Kotlin DSL"""
        lines = [
            "// Generated by Universal Dependency Resolver",
            f"// Date: {datetime.now().isoformat()}",
            "",
            "plugins {",
            '    id("java")',
            '    id("application")',
        ]
        
        # Add additional plugins
        if options.get('use_kotlin'):
            lines.append('    kotlin("jvm") version "1.9.0"')
        if options.get('use_spring'):
            lines.append('    id("org.springframework.boot") version "3.1.0"')
        
        lines.extend([
            "}",
            "",
            f'group = "{options.get("group_id", "com.example")}"',
            f'version = "{options.get("project_version", "1.0.0")}"',
            "",
            "java {",
            f'    sourceCompatibility = JavaVersion.VERSION_{options.get("java_version", "17")}',
            f'    targetCompatibility = JavaVersion.VERSION_{options.get("java_version", "17")}',
            "}",
            "",
            "repositories {",
            "    mavenCentral()",
        ])
        
        # Add custom repositories
        if custom_repos := options.get('repositories'):
            for repo in custom_repos:
                lines.append(f'    maven {{ url = uri("{repo}") }}')
        
        lines.extend([
            "}",
            "",
            "dependencies {"
        ])
        
        # Add Java packages
        java_packages = {
            name: info for name, info in packages.get('resolved_packages', {}).items() 
            if info.get('ecosystem') == 'maven'
        }
        
        # Group by scope
        implementation_deps = []
        test_deps = []
        runtime_deps = []
        
        for name, info in java_packages.items():
            version = info.get('version', '')
            scope = info.get('extras', {}).get('scope', 'implementation')
            
            if ':' in name:
                group_id, artifact_id = name.split(':', 1)
            else:
                group_id, artifact_id = 'unknown', name
            
            dep_string = f'"{group_id}:{artifact_id}:{version}"'
            
            if scope == 'test':
                test_deps.append(f"    testImplementation({dep_string})")
            elif scope == 'runtime':
                runtime_deps.append(f"    runtimeOnly({dep_string})")
            else:
                implementation_deps.append(f"    implementation({dep_string})")
        
        lines.extend(implementation_deps)
        lines.extend(runtime_deps)
        lines.extend(test_deps)
        
        # Add default test framework
        if options.get('include_testing', True):
            lines.append('    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")')
        
        lines.extend([
            "}",
            "",
            "application {",
            f'    mainClass.set("{options.get("main_class", "com.example.Main")}")',
            "}",
            "",
            "tasks.test {",
            "    useJUnitPlatform()",
            "}"
        ])
        
        # Add custom tasks
        if custom_tasks := options.get('custom_tasks'):
            lines.append("")
            for task_name, task_config in custom_tasks.items():
                lines.extend([
                    f'tasks.register("{task_name}") {{',
                    f'    {task_config}',
                    "}"
                ])
        
        return '\n'.join(lines)
    
    def _generate_maven(self, packages: Dict, system_info: Dict, options: Dict) -> str:
        """Generate pom.xml with modern features"""
        lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<project xmlns="http://maven.apache.org/POM/4.0.0"',
            '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
            '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0',
            '         https://maven.apache.org/xsd/maven-4.0.0.xsd">',
            '    <modelVersion>4.0.0</modelVersion>',
            '',
            f'    <groupId>{options.get("group_id", "com.example")}</groupId>',
            f'    <artifactId>{options.get("artifact_id", "my-app")}</artifactId>',
            f'    <version>{options.get("project_version", "1.0.0")}</version>',
            f'    <packaging>{options.get("packaging", "jar")}</packaging>',
            '',
            f'    <name>{options.get("project_name", "My Application")}</name>',
            f'    <description>{options.get("description", "Generated by Universal Dependency Resolver")}</description>',
            ''
        ]
        
        # Add properties
        java_version = options.get('java_version', '17')
        lines.extend([
            '    <properties>',
            f'        <maven.compiler.source>{java_version}</maven.compiler.source>',
            f'        <maven.compiler.target>{java_version}</maven.compiler.target>',
            '        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>',
            '        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>',
        ])
        
        # Add version properties for dependencies
        java_packages = {
            name: info for name, info in packages.get('resolved_packages', {}).items() 
            if info.get('ecosystem') == 'maven'
        }
        
        version_properties = {}
        for name, info in java_packages.items():
            if ':' in name:
                _, artifact_id = name.split(':', 1)
                version_key = f"{artifact_id.replace('-', '.')}.version"
                version_properties[version_key] = info.get('version', '')
        
        for key, value in version_properties.items():
            lines.append(f'        <{key}>{value}</{key}>')
        
        lines.extend([
            '    </properties>',
            ''
        ])
        
        # Add dependencies
        lines.append('    <dependencies>')
        
        for name, info in java_packages.items():
            if ':' in name:
                group_id, artifact_id = name.split(':', 1)
            else:
                group_id, artifact_id = 'unknown', name
            
            scope = info.get('extras', {}).get('scope', 'compile')
            
            lines.extend([
                '        <dependency>',
                f'            <groupId>{group_id}</groupId>',
                f'            <artifactId>{artifact_id}</artifactId>',
                f'            <version>${{{artifact_id.replace("-", ".")}.version}}</version>',
            ])
            
            if scope != 'compile':
                lines.append(f'            <scope>{scope}</scope>')
            
            lines.append('        </dependency>')
        
        lines.extend([
            '    </dependencies>',
            ''
        ])
        
        # Add build configuration
        lines.extend([
            '    <build>',
            '        <plugins>',
            '            <plugin>',
            '                <groupId>org.apache.maven.plugins</groupId>',
            '                <artifactId>maven-compiler-plugin</artifactId>',
            '                <version>3.11.0</version>',
            '                <configuration>',
            f'                    <source>{java_version}</source>',
            f'                    <target>{java_version}</target>',
            '                </configuration>',
            '            </plugin>',
        ])
        
        # Add additional plugins
        if options.get('include_surefire', True):
            lines.extend([
                '            <plugin>',
                '                <groupId>org.apache.maven.plugins</groupId>',
                '                <artifactId>maven-surefire-plugin</artifactId>',
                '                <version>3.1.2</version>',
                '            </plugin>',
            ])
        
        if options.get('include_jar_plugin', True):
            lines.extend([
                '            <plugin>',
                '                <groupId>org.apache.maven.plugins</groupId>',
                '                <artifactId>maven-jar-plugin</artifactId>',
                '                <version>3.3.0</version>',
                '                <configuration>',
                '                    <archive>',
                '                        <manifest>',
                f'                            <mainClass>{options.get("main_class", "com.example.Main")}</mainClass>',
                '                        </manifest>',
                '                    </archive>',
                '                </configuration>',
                '            </plugin>',
            ])
        
        lines.extend([
            '        </plugins>',
            '    </build>',
            '</project>'
        ])
        
        return '\n'.join(lines)


# Factory function for backward compatibility
def create_export_generator() -> ExportGenerator:
    """Create and return an ExportGenerator instance"""
    return ExportGenerator()