sonar.organization=code-with-zeeshan
sonar.projectKey=code-with-zeeshan_universal-dependency-resolver
sonar.sources=backend,frontend/src
sonar.tests=.
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
