"""initial.

Revision ID: 14896987c4e8
Revises:
Create Date: 2026-07-02 04:21:37.498399

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14896987c4e8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("packages",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("ecosystem", sa.String(length=50), nullable=False),
    sa.Column("latest_version", sa.String(length=50), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("homepage", sa.String(length=500), nullable=True),
    sa.Column("repository", sa.String(length=500), nullable=True),
    sa.Column("license", sa.String(length=100), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name", "ecosystem", name="_name_ecosystem_uc")
    )
    op.create_index("idx_package_ecosystem", "packages", ["ecosystem"], unique=False)
    op.create_index("idx_package_name", "packages", ["name"], unique=False)
    op.create_index("idx_package_name_ecosystem", "packages", ["name", "ecosystem"], unique=False)
    op.create_table("resolution_cache",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("request_hash", sa.String(length=64), nullable=True),
    sa.Column("packages", sa.JSON(), nullable=True),
    sa.Column("system_info", sa.JSON(), nullable=True),
    sa.Column("constraints", sa.JSON(), nullable=True),
    sa.Column("resolution", sa.JSON(), nullable=True),
    sa.Column("resolution_time_ms", sa.Integer(), nullable=True),
    sa.Column("success", sa.Boolean(), nullable=True),
    sa.Column("hit_count", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("request_hash")
    )
    op.create_index("idx_resolution_created", "resolution_cache", ["created_at"], unique=False)
    op.create_index("idx_resolution_expires", "resolution_cache", ["expires_at"], unique=False)
    op.create_index("idx_resolution_hash", "resolution_cache", ["request_hash"], unique=False)
    op.create_table("system_benchmarks",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("system_hash", sa.String(length=64), nullable=True),
    sa.Column("os_name", sa.String(length=50), nullable=True),
    sa.Column("os_version", sa.String(length=50), nullable=True),
    sa.Column("cpu_model", sa.String(length=255), nullable=True),
    sa.Column("cpu_cores", sa.Integer(), nullable=True),
    sa.Column("ram_gb", sa.Float(), nullable=True),
    sa.Column("gpu_model", sa.String(length=255), nullable=True),
    sa.Column("gpu_memory_gb", sa.Float(), nullable=True),
    sa.Column("system_info", sa.JSON(), nullable=True),
    sa.Column("benchmarks", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("system_hash")
    )
    op.create_index("idx_benchmark_hash", "system_benchmarks", ["system_hash"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("username", sa.String(length=50), nullable=False),
    sa.Column("email", sa.String(length=255), nullable=False),
    sa.Column("hashed_password", sa.String(length=255), nullable=False),
    sa.Column("full_name", sa.String(length=255), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=True),
    sa.Column("is_superuser", sa.Boolean(), nullable=True),
    sa.Column("scopes", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.Column("last_login", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("email"),
    sa.UniqueConstraint("username")
    )
    op.create_index("idx_user_email", "users", ["email"], unique=False)
    op.create_index("idx_user_username", "users", ["username"], unique=False)
    op.create_table("verified_combinations",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("packages", sa.JSON(), nullable=False),
    sa.Column("system_requirements", sa.JSON(), nullable=True),
    sa.Column("verified_by", sa.String(length=100), nullable=True),
    sa.Column("verification_date", sa.DateTime(), nullable=True),
    sa.Column("test_results", sa.JSON(), nullable=True),
    sa.Column("usage_count", sa.Integer(), nullable=True),
    sa.Column("success_rate", sa.Float(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_combination_created", "verified_combinations", ["created_at"], unique=False)
    op.create_index("idx_combination_name", "verified_combinations", ["name"], unique=False)
    op.create_table("api_keys",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("key", sa.String(length=255), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("scopes", sa.JSON(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=True),
    sa.Column("expires_at", sa.DateTime(), nullable=True),
    sa.Column("last_used_at", sa.DateTime(), nullable=True),
    sa.Column("usage_count", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("revoked_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("key")
    )
    op.create_index("idx_api_key", "api_keys", ["key"], unique=False)
    op.create_index("idx_api_key_active", "api_keys", ["is_active"], unique=False)
    op.create_index("idx_api_key_user", "api_keys", ["user_id"], unique=False)
    op.create_table("compatibility_reports",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("package_id", sa.Integer(), nullable=False),
    sa.Column("version", sa.String(length=50), nullable=False),
    sa.Column("os_name", sa.String(length=50), nullable=True),
    sa.Column("os_version", sa.String(length=50), nullable=True),
    sa.Column("cpu_architecture", sa.String(length=50), nullable=True),
    sa.Column("gpu_name", sa.String(length=255), nullable=True),
    sa.Column("cuda_version", sa.String(length=20), nullable=True),
    sa.Column("cudnn_version", sa.String(length=20), nullable=True),
    sa.Column("python_version", sa.String(length=20), nullable=True),
    sa.Column("system_info", sa.JSON(), nullable=True),
    sa.Column("works", sa.Boolean(), nullable=False),
    sa.Column("notes", sa.Text(), nullable=True),
    sa.Column("user_id", sa.String(length=100), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_report_created", "compatibility_reports", ["created_at"], unique=False)
    op.create_index("idx_report_package_version", "compatibility_reports", ["package_id", "version"], unique=False)
    op.create_table("conflict_rules",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("package1_id", sa.Integer(), nullable=False),
    sa.Column("package1_version_spec", sa.String(length=100), nullable=True),
    sa.Column("package2_id", sa.Integer(), nullable=False),
    sa.Column("package2_version_spec", sa.String(length=100), nullable=True),
    sa.Column("conflict_type", sa.String(length=50), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("severity", sa.String(length=20), nullable=True),
    sa.Column("resolution", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.Column("verified", sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(["package1_id"], ["packages.id"], ),
    sa.ForeignKeyConstraint(["package2_id"], ["packages.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("idx_conflict_packages", "conflict_rules", ["package1_id", "package2_id"], unique=False)
    op.create_table("package_versions",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("package_id", sa.Integer(), nullable=False),
    sa.Column("version", sa.String(length=50), nullable=False),
    sa.Column("release_date", sa.DateTime(), nullable=True),
    sa.Column("python_requires", sa.String(length=100), nullable=True),
    sa.Column("size_bytes", sa.Integer(), nullable=True),
    sa.Column("download_count", sa.Integer(), nullable=True),
    sa.Column("system_requirements", sa.JSON(), nullable=True),
    sa.Column("dependencies", sa.JSON(), nullable=True),
    sa.Column("metadata_json", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["package_id"], ["packages.id"], ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("package_id", "version", name="_package_version_uc")
    )
    op.create_index("idx_version_download_count", "package_versions", ["download_count"], unique=False)
    op.create_index("idx_version_package_id", "package_versions", ["package_id"], unique=False)
    op.create_index("idx_version_release_date", "package_versions", ["release_date"], unique=False)
    op.create_index("idx_version_version", "package_versions", ["version"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_version_version", table_name="package_versions")
    op.drop_index("idx_version_release_date", table_name="package_versions")
    op.drop_index("idx_version_package_id", table_name="package_versions")
    op.drop_index("idx_version_download_count", table_name="package_versions")
    op.drop_table("package_versions")
    op.drop_index("idx_conflict_packages", table_name="conflict_rules")
    op.drop_table("conflict_rules")
    op.drop_index("idx_report_package_version", table_name="compatibility_reports")
    op.drop_index("idx_report_created", table_name="compatibility_reports")
    op.drop_table("compatibility_reports")
    op.drop_index("idx_api_key_user", table_name="api_keys")
    op.drop_index("idx_api_key_active", table_name="api_keys")
    op.drop_index("idx_api_key", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("idx_combination_name", table_name="verified_combinations")
    op.drop_index("idx_combination_created", table_name="verified_combinations")
    op.drop_table("verified_combinations")
    op.drop_index("idx_user_username", table_name="users")
    op.drop_index("idx_user_email", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_benchmark_hash", table_name="system_benchmarks")
    op.drop_table("system_benchmarks")
    op.drop_index("idx_resolution_hash", table_name="resolution_cache")
    op.drop_index("idx_resolution_expires", table_name="resolution_cache")
    op.drop_index("idx_resolution_created", table_name="resolution_cache")
    op.drop_table("resolution_cache")
    op.drop_index("idx_package_name_ecosystem", table_name="packages")
    op.drop_index("idx_package_name", table_name="packages")
    op.drop_index("idx_package_ecosystem", table_name="packages")
    op.drop_table("packages")
    # ### end Alembic commands ###
